### ISSUE TITLE
Is it time to enlarge?

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#64] opened 2020-08-22 12:08 UTC
That's the case @stefanst recommends with higher chance of water tightness

![image](https://user-images.githubusercontent.com/48498823/90955810-98c74680-e44e-11ea-8eaf-34e04e5b50ae.png)

**Comment by mck1117** [comment] 2020-10-29 19:08
dupe of #67

**Closed by mck1117** 2020-10-29 19:08 UTC
